### ISSUE TITLE
IProducer.SendAsync and IConsumer.ReceiveMessage() hang and will not communicate with Artemis.

### ISSUE THREAD

**Issue by EdLichtman** [Havret/dotnet-activemq-artemis-client#444]
## Describe the bug 
When running the following code, my application pauses and doesn't continue. I'm completely unable to communicate with Artemis.

```await producer.SendAsync(message, cancellationToken).ConfigureAwait(false);```

Likewise, when I run producer.Send(message, cancellationToken), it works, but when listening for consumer via the next code, it pauses and doesn't continue.

```
  await this
                .consumer
                .AcceptAsync(message)
                .ConfigureAwait(false);
```

I need help figuring out how to debug what's going on, because I don't think it's behaving the way it's meant to.

## Expected behavior
I expect the message to be sent, and to be able to listen for messages.

## Environment:

- OS: Windows Server 2019
- Version: 2.12.0
- Broker: 2.23.1

## Additional context
Here is the code I'm using:

### The Client Factory

```
/// <summary>
/// ArtemisClientFactory.
/// </summary>
/// <seealso cref="Artemis.Client.Models.IArtemisClientFactory" />
public sealed class ArtemisClientFactory : IArtemisClientFactory
{
    /// <summary>
    /// The <see cref="ILoggerFactory"/>.
    /// </summary>
    private readonly ILoggerFactory loggerFactory;

    /// <summary>
    /// The <see cref="IArtemisClientSettings"/>.
    /// </summary>
    private readonly IArtemisClientSettings settings;

    /// <summary>
    /// Initializes a new instance of the <see cref="ArtemisClientFactory"/> class.
    /// </summary>
    /// <param name="loggerFactory">The <see cref="ILoggerFactory"/>.</param>
    /// <param name="settings">The <see cref="IArtemisClientSettings"/></param>
    public ArtemisClientFactory(
        ILoggerFactory loggerFactory,
        IArtemisClientSettings settings)
    {
        this.loggerFactory = loggerFactory;
        this.settings = settings;
    }

    /// <summary>
    /// Gets the artemis consumer client.
    /// </summary>
    /// <param name="routingType">Type of the routing.</param>
    /// <returns>The artemis consumer client.</returns>
    public async Task<IArtemisConsumerClient> GetArtemisConsumerClient(RoutingType routingType = RoutingType.Anycast)
    {
        return await ArtemisConsumerClient.CreateConsumer(
            this.loggerFactory,
            this.settings,
            routingType);
    }

    /// <summary>
    /// Gets the artemis producer client.
    /// </summary>
    /// <param name="routingType">Type of the routing.</param>
    /// <returns>The ArtemisProducerClient.</returns>
    public async Task<IArtemisProducerClient> GetArtemisProducerClient(RoutingType routingType = RoutingType.Anycast)
    {
        return await ArtemisProducerClient.CreateProducer(
            this.loggerFactory,
            this.settings,
            routingType);
    }
}

```

### The Configuration Settings
```
/// <summary>
/// The <see cref="IArtemisClientSettings"/> for opening a connection to Artemis.
/// </summary>
public interface IArtemisClientSettings
{
    /// <summary>
    /// Gets the Connection String.
    /// </summary>
    string ConnectionString { get; }

    /// <summary>
    /// Gets the Port for the message broker.
    /// </summary>
    int Port { get; }

    /// <summary>
    /// Gets the queue name for the message broker.
    /// </summary>
    string QueueName { get; }

    /// <summary>
    /// Gets the user name for the message broker.
    /// </summary>
    string UserName { get; }

    /// <summary>
    /// Gets the Password for the message broker.
    /// </summary>
    string Password { get; }
}
```

### The Producer Client
```
/// <summary>
/// The artemis producer client.
/// </summary>
internal sealed class ArtemisProducerClient : IArtemisProducerClient
{
    /// <summary>
    /// The Artemis Producer.
    /// </summary>
    private readonly IProducer? producer;

    /// <summary>
    /// The Timeout.
    /// </summary>
    private readonly TimeSpan timeout;

    /// <summary>
    /// Initializes a new instance of the <see cref="ArtemisProducerClient"/> class.
    /// </summary>
    /// <param name="producer">The producer.</param>
    /// <param name="timeout">The Timeout.</param>
    private ArtemisProducerClient(IProducer? producer, TimeSpan timeout)
    {
        this.producer = producer;
        this.timeout = timeout;
    }

    /// <summary>
    /// Creates the producer.
    /// </summary>
    /// <param name="loggerFactory">The <see cref="ILoggerFactory"/>.</param>
    /// <param name="settings">The <see cref="IArtemisClientSettings"/>.</param>
    /// <param name="routingType">Type of the routing.</param>
    /// <param name="timeoutInSeconds">Defaults to 20 seconds.  Period of time to wait before cancelling the sending of messages.</param>
    /// <returns>Task ArtemisProducerClient.</returns>
    public static async Task<ArtemisProducerClient> CreateProducer(
        ILoggerFactory loggerFactory,
        IArtemisClientSettings settings,
        RoutingType routingType,
        int timeoutInSeconds = 20)
    {
        var connectionFactory = new ConnectionFactory
        {
            LoggerFactory = loggerFactory,
            AutomaticRecoveryEnabled = false
        };

        var endpoint = Endpoint.Create(settings.ConnectionString, settings.Port, settings.UserName, settings.Password);

        var timeoutCancellationTokenSource = new CancellationTokenSource();
        timeoutCancellationTokenSource.CancelAfter(TimeSpan.FromSeconds(timeoutInSeconds));

        IConnection? connection = null;

        try
        {
            connection = await connectionFactory
                .CreateAsync(endpoint, timeoutCancellationTokenSource.Token)

                // .WaitAsync(timeoutCancellationTokenSource.Token)
                .ConfigureAwait(false);
        }
        catch (OperationCanceledException)
        {
            // Suppress this exception, as it will occur if there is no Artemis service running.
        }

        if (connection != null)
        {
            return new ArtemisProducerClient(
                await connection
                    .CreateProducerAsync(
                        new ProducerConfiguration
                        {
                            Address = settings.QueueName,
                            RoutingType = routingType,
                            MessageDurabilityMode = DurabilityMode.Nondurable
                        }, timeoutCancellationTokenSource.Token)
                    .ConfigureAwait(false),
                TimeSpan.FromSeconds(timeoutInSeconds));
        }
        else
        {
            return new ArtemisProducerClient(null, TimeSpan.FromSeconds(timeoutInSeconds));
        }
    }

    /// <summary>
    /// Produces the message.
    /// </summary>
    /// <param name="messageText">The message text.</param>
    /// <returns>A task that produces a message.</returns>
    public Task ProduceMessage(string messageText)
    {
        if (this.producer != null)
        {
            Message message = new(messageText);
            using var timeoutCancellationTokenSource = new CancellationTokenSource();
            timeoutCancellationTokenSource.CancelAfter(this.timeout);
            var cancellationToken = timeoutCancellationTokenSource.Token;
            this.producer.Send(message, cancellationToken);

            // await this.producer.SendAsync(message, cancellationToken).ConfigureAwait(false);
        }

        return Task.CompletedTask;
    }
}

```

### The ConsumerClient
```
/// <summary>
/// ArtemisConsumerClient.
/// </summary>
internal sealed class ArtemisConsumerClient : IArtemisConsumerClient
{
    /// <summary>
    /// The consumer.
    /// </summary>
    private readonly IConsumer? consumer;

    /// <summary>
    /// The timespan.
    /// </summary>
    private readonly TimeSpan timeout;

    /// <summary>
    /// Initializes a new instance of the <see cref="ArtemisConsumerClient"/> class.
    /// </summary>
    /// <param name="consumer">The consumer.</param>
    /// <param name="timeout">The timeout.</param>
    private ArtemisConsumerClient(IConsumer? consumer, TimeSpan timeout)
    {
        this.consumer = consumer;
        this.timeout = timeout;
    }

    /// <summary>
    /// Creates the consumer.
    /// </summary>
    /// <param name="loggerFactory">The <see cref="ILoggerFactory"/>.</param>
    /// <param name="settings">The connection string.</param>
    /// <param name="routingType">Type of the routing.</param>
    /// <param name="timeoutInSeconds">The timeout for requests, in seconds.</param>
    /// <returns>Task ArtemisConsumerClient.</returns>
    public static async Task<ArtemisConsumerClient> CreateConsumer(
        ILoggerFactory loggerFactory,
        IArtemisClientSettings settings,
        RoutingType routingType,
        Int32 timeoutInSeconds = 20)
    {
        var connectionFactory = new ConnectionFactory
        {
            LoggerFactory = loggerFactory,
            AutomaticRecoveryEnabled = false
        };
        var endpoint = Endpoint.Create(settings.ConnectionString, settings.Port, settings.UserName, settings.Password);
        var timeoutCancellationTokenSource = new CancellationTokenSource();
        timeoutCancellationTokenSource.CancelAfter(TimeSpan.FromSeconds(timeoutInSeconds));

        IConnection? connection = null;

        try
        {
            connection = await connectionFactory
                .CreateAsync(endpoint)

                // .WaitAsync(timeoutCancellationTokenSource.Token)
                .ConfigureAwait(false);
        }
        catch (OperationCanceledException)
        {
            // Suppress this exception, as it will occur if there is no Artemis service running
        }

        if (connection != null)
        {
            var consumer = await connection
                .CreateConsumerAsync(settings.QueueName, routingType);

            // .WaitAsync(timeoutCancellationTokenSource.Token).ConfigureAwait(false);
            return new ArtemisConsumerClient(consumer, TimeSpan.FromSeconds(timeoutInSeconds));
        }
        else
        {
            return new ArtemisConsumerClient(null, TimeSpan.FromSeconds(timeoutInSeconds));
        }
    }

    /// <summary>
    /// Receives the message.
    /// </summary>
    /// <returns>Task Message.</returns>
    public async Task<Message?> ReceiveMessage()
    {
        if (this.consumer != null)
        {
            using var timeoutCancellationTokenSource = new CancellationTokenSource();
            timeoutCancellationTokenSource.CancelAfter(this.timeout);
            var cancellationToken = timeoutCancellationTokenSource.Token;

            return await this
                .consumer
                .ReceiveAsync(cancellationToken)
                .ConfigureAwait(false);
        }
        else
        {
            return null;
        }
    }

    /// <summary>
    /// Accepts the message.
    /// </summary>
    /// <param name="message">The message.</param>
    public async void AcceptMessage(Message message)
    {
        if (this.consumer != null)
        {
            await this
                .consumer
                .AcceptAsync(message)
                .ConfigureAwait(false);
        }
    }
}
```

### The Creation of the factory/the test

```
[TestFixture]
public class ArtemisClientTests
{
    [Test]
    public async Task CanSendToAndReceiveMessagesFromArtemis()
    {
        var serviceCollection = new ServiceCollection();
        serviceCollection.AddLogging(loggingBuilder => loggingBuilder
            .AddFilter(
                "ActiveMQ.Artemis.Client.Producer",
                level => true)
            .AddFilter(
                "ActiveMQ.Artemis.Client.Consumer",
                level => true));

        serviceCollection.AddArtemisClient(s => new ArtemisClientSettings
        {
            ConnectionString = "redacted",
            Port = 5672,
            UserName = "redacted",
            Password = "redacted",
            QueueName = "redacted"
        });

        var factory = serviceCollection.BuildServiceProvider().GetRequiredService<IArtemisClientFactory>();
        var consumer = await factory.GetArtemisConsumerClient();
        var producer = await factory.GetArtemisProducerClient(RoutingType.Multicast);

        await producer.ProduceMessage("my-payload").ConfigureAwait(false);
        var message = await consumer.ReceiveMessage().ConfigureAwait(false);
        
        Assert.That(message.GetBody<string>(), Is.EqualTo("my-payload"));
    }
}
```
### Final words
You'll notice there's a couple of places where I comment out // .WaitAsync, because I found another issue that led me in the direction of "the guy using the code was adding .Wait to the end. In addition, it was suggested to that person to add .ConfigureAwait(false) everywhere, and I have added it to every instance of a method that returns a Task.

The big problems is that in the final lines of the integration test, when I run producer.SendAsync in the producer facade, it just waits for 20 seconds and the test fails. If I comment it out like you see in the code above, and move to the next line, await consumer.ReceiveMessage().ConfigureAwait(false), then likewise, it waits 20 seconds and then the test fails.

And I added a LoggerFactory that always returns true in any log level when the category is one of the two artemis categories, and yet I see nothing presented in the logs.

**Comment by Havret** [comment]
Hi [EdLichtman](https://github.com/EdLichtman),

The problem with code is that you're sending a message using multicast routing type and and then you're trying to consume it using anycast consumer. 

To rectify this, consider modifying your test code as follows:

```
var producer = await factory.GetArtemisProducerClient(RoutingType.Multicast);
var consumer = await factory.GetArtemisConsumerClient(RoutingType.Multicast);
```

Doing this should solve the problem. Presently, your application is in a suspended state because it's awaiting a message that never arrives.

For a more in-depth understanding of the Artemis Address Model, I recommend reading this [article](https://havret.io/activemq-artemis-address-model). This should provide some clarity on the matter.

Best,
Havret

**Comment by EdLichtman** [comment]
Hi @Havret,

Briefly looking into the article, it seems I should also be able to fix this by making them Anycast instead of Multicast, however when I set them both to Anycast, the issue persists. Am I misunderstanding?

**Comment by Havret** [comment]
You're absolutely right. However, please be aware that if you've previously executed this code using the Multicast routing type with the same address, any new configurations might be disregarded.

**Comment by EdLichtman** [comment]
It still doesn't seem to be working when I line them up with a new target queue... but I think I found out what may be causing it to be "hanging forever"

2023-06-27 12:29:17,554 WARN  [org.apache.activemq.artemis.core.server] AMQ222212: Disk Full! Blocking message production on address 'ArtemisClientIntegrationTests2'. Clients will report blocked.

Would this message hold open the ProduceMessage connection indefinitely?

**Comment by Havret** [comment]
Based on the quick look at the Artemis source code, it appears to be so. However, for a definitive answer, I recommend reaching out to the Artemis maintainers directly via their [user mailing list](https://activemq.apache.org/contact#mailing).

I don't have much experience with overflown addresses, as keeping the queues and addresses short is essential for proper broker behavior.

**Comment by EdLichtman** [comment]
Yup, I deleted some disk space and then found the following configuration in the logs:

      
      <max-disk-usage>90</max-disk-usage>

Setting that to 98 and I could continue.
